language: csharp
dist: xenial
os: linux

branches:
  except:
  - /^[0-9]/

dotnet: 3.1
mono: none
  
install:
  - dotnet restore
  
script:
  - (git fetch --unshallow 2>/dev/null || echo "Already full repo.")
  - ./build.sh

notifications:
  on_success: always
  on_failure: always
