image: Visual Studio 2017

install:
  - cinst msys2
  - set PATH=C:\msys64\usr\bin;%PATH%

build_script:
  - bash.exe -lc "cd $APPVEYOR_BUILD_FOLDER && ./etc/scripts/write_version_targets.sh"
  - ps: .\build.ps1 -VersionAndPublish (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER)

test: off

artifacts:
- path: .\**\*.nupkg
  name: NuGet
  
nuget:
  disable_publish_on_pr: true 
  
deploy:  
- provider: NuGet
  api_key:
    secure: K7GBfAz5cr3lqVzn2+KbM45GA2ZeDjOpgnDU2jpw76PxBL2Qph3OBcfXWuGb+wwD
  on:
    appveyor_repo_tag: true
