image: Visual Studio 2017

skip_tags: true

install:
  - cinst msys2
  - set PATH=C:\msys64\usr\bin;%PATH%

build_script:
  - bash.exe -lc "./etc/scripts/write_version_targets.sh"
  - ps: .\build.ps1 -VersionAndPublish (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER)

test: off
